/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnidemo_JniInterfaceTest */

#ifndef _Included_com_example_jnidemo_JniInterfaceTest
#define _Included_com_example_jnidemo_JniInterfaceTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnidemo_JniInterfaceTest
 * Method:    jniInterface1
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_jnidemo_JniInterfaceTest_jniInterface1
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_jnidemo_JniInterfaceTest
 * Method:    jniInterface2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnidemo_JniInterfaceTest_jniInterface2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
